from django.urls import path
from .views import (
    ADRReportCreateView,
    AIAssistantView,
    BatchQualityTestListCreateView,
    BatchQRExportView,
    BatchReleaseView,
    ComplianceDashboardView,
    PharmacyBatchVerifyView,
    PharmacyCitizenLookupView,
    PharmacyComplaintListView,
    PharmacyComplaintResolveView,
    PharmacyDashboardView,
    PharmacyDemandForecastView,
    PharmacyExpiryAlertsView,
    PharmacyRecallAlertsView,
    PharmacyRiskAlertsView,
    PharmacySaleListCreateView,
    DemandForecastView,
    DistributionEventListCreateView,
    DistributorAnalyticsView,
    DistributorFleetMonitoringView,
    DistributorIncomingShipmentListView,
    DistributorOutgoingShipmentDetailView,
    DistributorOutgoingShipmentListCreateView,
    DistributorRouteOptimizationView,
    DistributorRouteRiskView,
    DistributorShipmentLocationUpdateView,
    DistributorShipmentReceiveView,
    DistributorWarehouseDetailView,
    DistributorWarehouseListCreateView,
    DrugPassportView,
    ManufacturerBatchDetailView,
    ManufacturerBatchListCreateView,
    ManufacturerDashboardView,
    ManufacturerMedicineListCreateView,
    NotificationListView,
    NotificationMarkReadView,
    InteractionCheckerView,
    PharmacyFinderView,
    PharmacyInventoryDetailView,
    PharmacyInventoryListCreateView,
    PharmacyShipmentListView,
    PharmacyShipmentReceiveView,
    PersonalMedicineRecordDetailView,
    PersonalMedicineRecordView,
    RecallListCreateView,
    CitizenDashboardView,
)
from .dgda_views import (
    DGDACommandCenterView,
    DGDABatchTrackingView,
    DGDACounterfeitInvestigationView,
    DGDARecallViewSet,
    DGDAInspectionViewSet,
    DGDAEntityMonitoringView,
    DGDAHeatmapDataView,
    DGDAAIRiskIntelligenceView,
    DGDAPolicyAnalyticsView,
    DGDAEmergencyResponseView,
)

urlpatterns = [
    path('passport/<str:qr_code>/', DrugPassportView.as_view(), name='drug-passport'),
    path('medicines/personal/', PersonalMedicineRecordView.as_view(), name='personal-medicines'),
    path('medicines/personal/<int:pk>/', PersonalMedicineRecordDetailView.as_view(), name='personal-medicines-detail'),
    path('adr/', ADRReportCreateView.as_view(), name='adr-report'),
    path('pharmacies/', PharmacyFinderView.as_view(), name='pharmacy-finder'),
    path('notifications/', NotificationListView.as_view(), name='notifications'),
    path('notifications/<int:pk>/read/', NotificationMarkReadView.as_view(), name='notification-mark-read'),
    path('ai-assistant/', AIAssistantView.as_view(), name='ai-assistant'),
    path('interaction-checker/', InteractionCheckerView.as_view(), name='interaction-checker'),
    path('citizen/dashboard/', CitizenDashboardView.as_view(), name='citizen-dashboard'),
    path('manufacturer/dashboard/', ManufacturerDashboardView.as_view(), name='manufacturer-dashboard'),
    path('manufacturer/medicines/', ManufacturerMedicineListCreateView.as_view(), name='manufacturer-medicines'),
    path('manufacturer/batches/', ManufacturerBatchListCreateView.as_view(), name='manufacturer-batches'),
    path('manufacturer/batches/<int:pk>/', ManufacturerBatchDetailView.as_view(), name='manufacturer-batch-detail'),
    path('manufacturer/batches/<int:pk>/release/', BatchReleaseView.as_view(), name='manufacturer-batch-release'),
    path('manufacturer/batches/<int:pk>/qr-export/', BatchQRExportView.as_view(), name='manufacturer-batch-qr-export'),
    path('manufacturer/batches/<int:pk>/quality-tests/', BatchQualityTestListCreateView.as_view(), name='manufacturer-batch-quality-tests'),
    path('manufacturer/batches/<int:pk>/distribution-events/', DistributionEventListCreateView.as_view(), name='manufacturer-batch-distribution-events'),
    path('manufacturer/recalls/', RecallListCreateView.as_view(), name='manufacturer-recalls'),
    path('manufacturer/compliance/', ComplianceDashboardView.as_view(), name='manufacturer-compliance'),
    path('manufacturer/demand-forecast/', DemandForecastView.as_view(), name='manufacturer-demand-forecast'),
    path('pharmacy/inventory/', PharmacyInventoryListCreateView.as_view(), name='pharmacy-inventory'),
    path('pharmacy/inventory/<int:pk>/', PharmacyInventoryDetailView.as_view(), name='pharmacy-inventory-detail'),
    path('pharmacy/shipments/', PharmacyShipmentListView.as_view(), name='pharmacy-shipments'),
    path('pharmacy/shipments/<int:pk>/receive/', PharmacyShipmentReceiveView.as_view(), name='pharmacy-shipment-receive'),
    path('pharmacy/verify/<str:qr_code>/', PharmacyBatchVerifyView.as_view(), name='pharmacy-batch-verify'),
    path('pharmacy/citizens/lookup/', PharmacyCitizenLookupView.as_view(), name='pharmacy-citizen-lookup'),
    path('pharmacy/sales/', PharmacySaleListCreateView.as_view(), name='pharmacy-sales'),
    path('pharmacy/recalls/', PharmacyRecallAlertsView.as_view(), name='pharmacy-recall-alerts'),
    path('pharmacy/expiry-alerts/', PharmacyExpiryAlertsView.as_view(), name='pharmacy-expiry-alerts'),
    path('pharmacy/demand-forecast/', PharmacyDemandForecastView.as_view(), name='pharmacy-demand-forecast'),
    path('pharmacy/complaints/', PharmacyComplaintListView.as_view(), name='pharmacy-complaints'),
    path('pharmacy/complaints/<int:pk>/resolve/', PharmacyComplaintResolveView.as_view(), name='pharmacy-complaint-resolve'),
    path('pharmacy/risk-alerts/', PharmacyRiskAlertsView.as_view(), name='pharmacy-risk-alerts'),
    path('pharmacy/dashboard/', PharmacyDashboardView.as_view(), name='pharmacy-dashboard'),
    path('distributor/warehouses/', DistributorWarehouseListCreateView.as_view(), name='distributor-warehouses'),
    path('distributor/warehouses/<int:pk>/', DistributorWarehouseDetailView.as_view(), name='distributor-warehouse-detail'),
    path('distributor/shipments/incoming/', DistributorIncomingShipmentListView.as_view(), name='distributor-shipments-incoming'),
    path('distributor/shipments/incoming/<int:pk>/receive/', DistributorShipmentReceiveView.as_view(), name='distributor-shipment-receive'),
    path('distributor/shipments/outgoing/', DistributorOutgoingShipmentListCreateView.as_view(), name='distributor-shipments-outgoing'),
    path('distributor/shipments/outgoing/<int:pk>/', DistributorOutgoingShipmentDetailView.as_view(), name='distributor-shipment-outgoing-detail'),
    path('distributor/analytics/', DistributorAnalyticsView.as_view(), name='distributor-analytics'),
    path('distributor/route-optimization/', DistributorRouteOptimizationView.as_view(), name='distributor-route-optimization'),
    path('distributor/fleet-monitoring/', DistributorFleetMonitoringView.as_view(), name='distributor-fleet-monitoring'),
    path('distributor/fleet-monitoring/<int:pk>/update-location/', DistributorShipmentLocationUpdateView.as_view(), name='distributor-fleet-update-location'),
    path('distributor/route-risk/', DistributorRouteRiskView.as_view(), name='distributor-route-risk'),

    # DGDA Portal Routes
    path('dgda/command-center/', DGDACommandCenterView.as_view(), name='dgda-command-center'),
    path('dgda/batch/<str:batch_number>/', DGDABatchTrackingView.as_view(), name='dgda-batch-tracking'),
    path('dgda/investigations/', DGDACounterfeitInvestigationView.as_view(), name='dgda-investigations'),
    path('dgda/recalls/', DGDARecallViewSet.as_view({'get': 'list', 'post': 'create'}), name='dgda-recalls'),
    path('dgda/inspections/', DGDAInspectionViewSet.as_view({'get': 'list', 'post': 'create'}), name='dgda-inspections'),
    path('dgda/entities/', DGDAEntityMonitoringView.as_view(), name='dgda-entities'),
    path('dgda/heatmaps/', DGDAHeatmapDataView.as_view(), name='dgda-heatmaps'),
    path('dgda/risk-intelligence/', DGDAAIRiskIntelligenceView.as_view(), name='dgda-risk-intelligence'),
    path('dgda/policy-analytics/', DGDAPolicyAnalyticsView.as_view(), name='dgda-policy-analytics'),
    path('dgda/emergency-response/', DGDAEmergencyResponseView.as_view(), name='dgda-emergency-response'),
]
