# Generated by Django 6.0.7 on 2026-08-06 14:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_dosageschedule"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="batch",
            name="api_sources",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name="batch",
            name="ddp_id",
            field=models.CharField(
                blank=True,
                db_index=True,
                editable=False,
                max_length=64,
                null=True,
                unique=True,
            ),
        ),
        migrations.AddField(
            model_name="batch",
            name="geo_timestamp",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="batch",
            name="ingredients",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name="batch",
            name="qc_results",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name="batch",
            name="qc_status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("passed", "Passed"),
                    ("failed", "Failed"),
                ],
                default="pending",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="batch",
            name="qr_activated_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="batch",
            name="release_blocked",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="batch",
            name="unit_qr_codes",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name="batch",
            name="warehouse_released_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="medicine",
            name="formulation",
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AddField(
            model_name="medicine",
            name="is_registered",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="medicine",
            name="packaging",
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AddField(
            model_name="medicine",
            name="product_id",
            field=models.CharField(
                blank=True,
                db_index=True,
                editable=False,
                max_length=40,
                null=True,
                unique=True,
            ),
        ),
        migrations.AddField(
            model_name="medicine",
            name="quality_certificate",
            field=models.FileField(
                blank=True, null=True, upload_to="quality-certificates/"
            ),
        ),
        migrations.AddField(
            model_name="medicine",
            name="regulatory_approval_number",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="qualitytest",
            name="is_out_of_spec",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="qualitytest",
            name="result_value",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="recall",
            name="halted_sales",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="recall",
            name="notified_downstream_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="recall",
            name="progress_percent",
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="shipment",
            name="geo_location",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="shipment",
            name="geo_timestamp",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="adrreport",
            name="attachment",
            field=models.FileField(blank=True, null=True, upload_to="adr-attachments/"),
        ),
        migrations.AlterField(
            model_name="batch",
            name="qr_code",
            field=models.CharField(
                blank=True, editable=False, max_length=255, null=True, unique=True
            ),
        ),
        migrations.AlterField(
            model_name="inspection",
            name="report_file",
            field=models.FileField(
                blank=True, null=True, upload_to="inspection-reports/"
            ),
        ),
        migrations.AlterField(
            model_name="qualitytest",
            name="report_file",
            field=models.FileField(blank=True, null=True, upload_to="qc-reports/"),
        ),
        migrations.AlterField(
            model_name="researchdataset",
            name="data_file",
            field=models.FileField(
                blank=True, null=True, upload_to="research-datasets/"
            ),
        ),
        migrations.CreateModel(
            name="ComplianceItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=150)),
                ("due_date", models.DateField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("submitted", "Submitted"),
                            ("approved", "Approved"),
                            ("expired", "Expired"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                (
                    "evidence_file",
                    models.FileField(
                        blank=True, null=True, upload_to="compliance-evidence/"
                    ),
                ),
                ("notes", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="compliance_items",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="DemandForecast",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("region", models.CharField(db_index=True, max_length=100)),
                ("forecast_date", models.DateField()),
                ("predicted_demand", models.PositiveIntegerField()),
                (
                    "confidence_score",
                    models.DecimalField(decimal_places=2, default=0.5, max_digits=4),
                ),
                (
                    "seasonal_signal",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("source_summary", models.JSONField(blank=True, default=list)),
                ("notes", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="demand_forecasts",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="DistributionEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("stage_from", models.CharField(max_length=50)),
                ("stage_to", models.CharField(max_length=50)),
                ("quantity", models.PositiveIntegerField()),
                ("event_date", models.DateTimeField(auto_now_add=True)),
                (
                    "geo_location",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("geo_timestamp", models.DateTimeField(auto_now_add=True)),
                ("notes", models.TextField(blank=True, null=True)),
                (
                    "batch",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="distribution_events",
                        to="core.batch",
                    ),
                ),
                (
                    "from_user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="distribution_events_sent",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "to_user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="distribution_events_received",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
