# Generated by Django 6.0.1 on 2026-09-15 08:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_monitoringevent_citizen_monitoringevent_distributor_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CounterfeitReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qr_code', models.CharField(blank=True, db_index=True, max_length=255, null=True)),
                ('medicine_name', models.CharField(max_length=150)),
                ('location', models.CharField(blank=True, max_length=255, null=True)),
                ('category', models.CharField(choices=[('wrong_packaging', 'Wrong Packaging'), ('suspicious_price', 'Suspicious Price'), ('failed_verification', 'Failed Verification'), ('other', 'Other')], max_length=30)),
                ('description', models.TextField()),
                ('photo', models.FileField(blank=True, null=True, upload_to='counterfeit-reports/')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('reviewed', 'Reviewed'), ('confirmed', 'Confirmed'), ('dismissed', 'Dismissed')], db_index=True, default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('reporter', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='counterfeit_reports', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
