# Generated by Django 6.0.1 on 2026-09-25 22:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_counterfeitreport'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ShipmentLocationCheckIn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(max_length=255)),
                ('district', models.CharField(blank=True, max_length=100, null=True)),
                ('reported_at', models.DateTimeField(auto_now_add=True)),
                ('reported_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='shipment_checkins', to=settings.AUTH_USER_MODEL)),
                ('shipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='location_checkins', to='core.shipment')),
            ],
            options={
                'ordering': ['reported_at'],
                'indexes': [models.Index(fields=['shipment', 'reported_at'], name='core_shipme_shipmen_20c65d_idx')],
            },
        ),
    ]
