# Generated by Django 5.2.15 on 2026-09-28 02:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_consultation_consultation_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='consultationmessage',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to='consultation-attachments/'),
        ),
        migrations.AlterField(
            model_name='consultationmessage',
            name='message',
            field=models.TextField(blank=True, default=''),
        ),
    ]
